apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frostgate-core.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "frostgate-core.name" . }}
    helm.sh/chart: {{ include "frostgate-core.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: "{{ $v }}"
  {{- end }}