{{- if not .Values.secrets.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frostgate-core.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "frostgate-core.name" . }}
    helm.sh/chart: {{ include "frostgate-core.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  frostgate-api-key: {{ default "" .Values.secrets.frostgateApiKey | b64enc }}
{{- end }}
