apiVersion: v1
kind: ServiceAccount
metadata:
  name: frostgate-core-frostgate-core
  labels:
    app.kubernetes.io/name: frostgate-core
    helm.sh/chart: frostgate-core-0.1.0
    app.kubernetes.io/instance: frostgate-core
    app.kubernetes.io/managed-by: Helm
