kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: frostgate-dev
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 8080
        hostPort: 18080
        protocol: TCP
      - containerPort: 9090
        hostPort: 19090
        protocol: TCP
